export const IS_AUTHENTICATION = "IS_AUTHENTICATION"
export const SET_SISWA = "SET_SISWA"
export const SET_PENULIS = "SET_PENULIS"
export const SET_USER = "SET_USER"
export const SET_WACANAS = "SET_WACANAS"
export const SET_WACANA = "SET_WACANA"
export const SET_ARTICLES = "SET_ARTICLES"
export const SET_ARTICLE = "SET_ARTICLE"
